version: '3.7'
services:
    paypal-sandbox-dashboard:
        container_name: "paypal-sandbox-dashboard"
        build:
            context: . 
            network: ppsd-net
        environment:
            - MONGO_URI=mongodb://mongodb:27017
            - REACT_APP_HOST=${REACT_APP_HOST}
        ports:
            - "3000:3000"
        networks:
            - ppsd-net
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        ports:
            - 27017:27017
        command: mongod --quiet
        networks:
            - ppsd-net
networks:
    ppsd-net:
        name: ppsd-net
        driver: bridge
